import type { Metadata } from "next"
import { Geist, Geist_Mono } from "next/font/google"
import "./globals.css"
import Filmgrain from "./components/Filmgrain"
import { ContextProvider } from "./context"

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
})

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body>
        <main
          className={`${geistSans.variable} ${geistMono.variable} relative mx-auto flex min-h-screen flex-col antialiased`}
        >
          {/* <Filmgrain /> */}

          <ContextProvider>{children}</ContextProvider>
        </main>
      </body>
    </html>
  )
}
